fix🐛: 修复了linux6.1内核下硬件加速被错误关闭的bug
Sherlockouo/music pull request #145
Opened 2024-10-03 11:12 UTC by jcfun

修复了linux6.1*内核下硬件加速被错误关闭的bug

2024-10-03 12:21 UTC, pan93412 requested changes

2024-10-03 12:21 UTC, pan93412 commented on pnpm-lock.yaml
這個 PR 應該不用更新 lockfile 的

2024-10-04 09:44 UTC, jcfun commented on pnpm-lock.yaml
抱歉，没注意到，挺久之前拉的代码了

2024-10-04 09:48 UTC, closed without merging

2024-10-04 10:18 UTC, pan93412 commented
@jcfun 你誤 close 了？

2024-10-05 13:25 UTC, jcfun commented
> @jcfun 你誤 close 了？

我主动关闭的，我清理了一下仓库重新提了一个pr