feat: control area redesign & login beautify
Sherlockouo/music pull request #37
Opened 2023-10-22 04:07 UTC by yuzh0816

founded bug: playlist height is too high.

2023-10-22 04:15 UTC, pan93412 requested changes

2023-10-22 04:15 UTC, pan93412 commented on packages/web/components/NowPlaying/NowPlaying.tsx
> +
space here should be stripped out

2023-10-28 09:01 UTC, Sherlockouo commented
冲突需要解下，在小屏幕的机器，playlist部分会被挤的很小。
<img width="1259" alt="image" src="https://github.com/Sherlockouo/music/assets/34598208/55ad0fd7-a720-405b-a80a-6a9fe234c5fd">

2023-11-04 13:59 UTC, closed without merging

2023-11-04 14:01 UTC, yuzh0816 commented
Disgarded.